title: Replace this line with your name
description: A template for your AOS C111/204 project site.
logo: /assets/IMG/template_logo.png
show_downloads: true
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
